LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Chrome
LOCAL_MODULE_OWNER := Google
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.1847.114
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.1916.122
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.1916.138
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.1916.141
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.1985.122
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.1985.128
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.1985.131
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.1985.135
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.2062.117
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.2125.102
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.2125.114
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.2171.37
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome.2171.59
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchrome
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchromeview
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libchromium_android_linker
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS)/Chrome/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)
