LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Velvet
LOCAL_MODULE_OWNER := Google
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libcronet
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/Velvet/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgoogle_speech_jni
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/Velvet/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgoogle_speech_micro_jni
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/Velvet/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)
