LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := GmsCore
LOCAL_MODULE_OWNER := Google
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libAppDataSearch
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libconscrypt_gmscore_jni
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libdirect-audio
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgcastv2_base
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgcastv2_support
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgmscore
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgms-ocrclient
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libjgcastservice
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libNearbyApp
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libsslwrapper_jni
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libwearable-selector
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libWhisper
LOCAL_SRC_FILES := lib/arm/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_APPS_PRIVILEGED)/GmsCore/lib/arm/
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := Google
include $(BUILD_PREBUILT)
